In [2]:
import torch
import numpy as np

### 1-D Scalar Vectors

In [2]:
x = torch.empty(1)
print(x)

tensor([2.5420e-21])


In [4]:
y = torch.empty(3)
print(y)

tensor([0., 0., 0.])


### 2-D Scalar Vectors

In [5]:
x = torch.empty(2, 3)
print(x)

tensor([[2.5676e-21, 1.4658e-42, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00]])


### Tensors with random value

In [10]:
x = torch.rand(2,2)
#x = torch.ones(2,2, dtype = torch.int)
print(x)
print(x.dtype)
print(x.size())

tensor([[0.7526, 0.5866],
        [0.0453, 0.7136]])
torch.float32
torch.Size([2, 2])


### Create a tensor as a list

In [11]:
x = torch.tensor([0.1,0.4])
print(x)

tensor([0.1000, 0.4000])


### Mathematical Calculations

In [14]:
x = torch.rand(2,2)
y = torch.rand(2,2)

print(x)
print(y)

'''
1. Element-wise addition:
    z = x + y;
    z = torch.add(x,y);
2. In-Place addition:
    y = y.add_(x); -> adds all elements of x to y *"_" will perform inplace operations in tensor*
3. Element-wise Substraction:
    z = x - y;
    z = torch.sun(x,y);
4. Same goes for Multiplication and division
'''

#addition
z = x+y
print(z)

#inplace
y.add_(x)
print(y)

tensor([[0.3798, 0.8165],
        [0.6432, 0.9722]])
tensor([[0.2060, 0.3257],
        [0.8649, 0.4986]])
tensor([[0.5857, 1.1422],
        [1.5081, 1.4709]])
tensor([[0.5857, 1.1422],
        [1.5081, 1.4709]])


### Slicing

In [15]:
x = torch.rand(3,5)
print(x)

tensor([[0.8592, 0.9970, 0.6570, 0.6712, 0.8746],
        [0.9078, 0.2360, 0.8089, 0.3629, 0.5596],
        [0.1778, 0.2071, 0.1920, 0.2487, 0.8640]])


In [17]:
# take all rows but 1st column
print(x[:,0])

#take all columns but 1st row
print(x[0,:])

tensor([0.8592, 0.9078, 0.1778])
tensor([0.8592, 0.9970, 0.6570, 0.6712, 0.8746])


### Reshaping a Tensor

In [18]:
x = torch.rand(4,4)
print(x)

tensor([[0.5855, 0.3948, 0.7523, 0.4426],
        [0.3367, 0.3425, 0.4390, 0.6903],
        [0.9553, 0.8767, 0.3314, 0.8681],
        [0.3490, 0.0107, 0.7934, 0.8874]])


In [19]:
#lets convert it into 1-D vector
y = x.view(16)
print(y)

tensor([0.5855, 0.3948, 0.7523, 0.4426, 0.3367, 0.3425, 0.4390, 0.6903, 0.9553,
        0.8767, 0.3314, 0.8681, 0.3490, 0.0107, 0.7934, 0.8874])


In [21]:
'''
-1 means it will resize the columns or row according to the ggiven column or row.
'''
y = x.view(-1, 4)
print(y)
print(y.size())

tensor([[0.5855, 0.3948, 0.7523, 0.4426],
        [0.3367, 0.3425, 0.4390, 0.6903],
        [0.9553, 0.8767, 0.3314, 0.8681],
        [0.3490, 0.0107, 0.7934, 0.8874]])
torch.Size([4, 4])


### Converting Numpy to Tensor and Vice-verca

In [29]:
# Torch to Numpy

x = torch.ones(5)
print(x)
y = x.numpy()
print(y)
print(type(y))


tensor([1., 1., 1., 1., 1.])
[1. 1. 1. 1. 1.]
<class 'numpy.ndarray'>


In [30]:
'''
1. If the tensor is on CPU and not GPU, then both the tensor and numpy will share same memory location.
2. So if any changes is made in tensor, it will reflect on numpy array.
'''
x = x.sub_(1)
print(x)
print(y)

tensor([0., 0., 0., 0., 0.])
[0. 0. 0. 0. 0.]


In [36]:
# Numpy to Torch

x = np.ones(5)
print(x)
y = torch.from_numpy(x)
print(y)

[1. 1. 1. 1. 1.]
tensor([1., 1., 1., 1., 1.], dtype=torch.float64)


In [39]:
x += 1
print(x)


[3. 3. 3. 3. 3.]


In [40]:
print(y)

tensor([3., 3., 3., 3., 3.], dtype=torch.float64)


### GPU

In [7]:
'''
1. We cannot convert a GPU tensor to Numpy.
2. Move to GPU by using:
    x = torch.ones(5, device=device)
    y = torch.ones(5)
    y = y.to(device)
'''

# torch.cuda.is_available()

if torch.cuda.is_available:
    device = torch.device("cuda")
    x = torch.ones(5, device=device)
    y = torch.ones(5)
    y = y.to(device)
    z = x + y
    # print(z)
    z = z.to("cpu")